### ISSUE TITLE
Looks like someone is trying to use fast render to load external information?

### ISSUE THREAD

**Issue by patrickml** [kadirahq/fast-render#172]
On my server I am seeing odd errors like this. It seems like they may be trying to have my server render the html for them, like a proxy? any ideas?
```
Error: url must be a relative URL: http://a0.50na50.net/myiphd.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146631357869231
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://hideface.tk/myiphc.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146631357882265
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://50na50.net/myiphd.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146631357895244
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://www.baidu.com/
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
[192.241.186.183] Error: url must be a relative URL: http://www.baidu.com/
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://tiras.tk/myiphc.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146638501623027
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://b1.50na50.net/myiphd.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146638501649300
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
[192.241.186.183]     at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
[192.241.186.183]     at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
[192.241.186.183] Error: url must be a relative URL: http://hideface.tk/myiphc.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146638501662494
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://50na50.net/myiphd.php?rnd=82a51e245cbc70cdedbcc74be165373a&rn=146638501675631
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://www.baidu.com/
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
Error: url must be a relative URL: http://www.mafengwo.cn/
    at [object Object]._.extend.classify (packages/routepolicy.js:126:13)
    at IsAppUrl (packages/meteorhacks_fast-render.js:163:18)
    at [object Object].filterFunction (packages/meteorhacks_fast-render.js:193:10)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:66:23)
    at processNextSubRouter (packages/meteorhacks_picker.js:102:17)
    at processNextRoute (packages/meteorhacks_picker.js:95:7)
    at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
    at [object Object].PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
    at Object.Package [as handle] (packages/meteorhacks_picker.js:162:10)
    at next (/bundle/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/proto.js:174:15)
```

**Comment by s7dhansh** [comment]
+1. any information or solution?

**Comment by akmalhisyam** [comment]
probably just a bot scanning for bad proxy configuration.
If you proxy you app via httpd or nginx you should see lots of entry such as

```
37.26.128.179 - - [17/Aug/2016:08:04:44 +0800] "CONNECT a0.50na50.net:80 HTTP/1.1" 405 304 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0"
```
